-- Typed models for the Nofrixion SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Account
---@field accountBalances? table
---@field accountID? string
---@field accountIdentifications? table
---@field accountName? string
---@field accountNames? table
---@field accountSupplierName? string
---@field accountType? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field consolidatedAccountInformation? table
---@field createdBy table
---@field createdByDisplayName? string
---@field currency? string
---@field defaultPaymentRail? string
---@field description? string
---@field details? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field format? string
---@field fromDate? string
---@field id? string
---@field identifier table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field nickname? string
---@field physicalAccountID? string
---@field roleIDs? table
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierPhysicalAccountID? string
---@field supplierSepaInstantStatus? string
---@field toDate? string
---@field type? string
---@field usageType? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class AccountLoadMatch
---@field account_id? string
---@field id string
---@field merchant_id? string

---@class AccountListMatch
---@field accountBalances? table
---@field accountID? string
---@field accountIdentifications? table
---@field accountName? string
---@field accountNames? table
---@field accountSupplierName? string
---@field accountType? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field consolidatedAccountInformation? table
---@field createdBy? table
---@field createdByDisplayName? string
---@field currency? string
---@field defaultPaymentRail? string
---@field description? string
---@field details? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field format? string
---@field fromDate? string
---@field id? string
---@field identifier? table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field nickname? string
---@field physicalAccountID? string
---@field roleIDs? table
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierPhysicalAccountID? string
---@field supplierSepaInstantStatus? string
---@field toDate? string
---@field type? string
---@field usageType? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class AccountCreateData
---@field account_id string
---@field currency string
---@field accountBalances? table
---@field accountID? string
---@field accountIdentifications? table
---@field accountName? string
---@field accountNames? table
---@field accountSupplierName? string
---@field accountType? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field consolidatedAccountInformation? table
---@field createdBy table
---@field createdByDisplayName? string
---@field defaultPaymentRail? string
---@field description? string
---@field details? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field format? string
---@field fromDate? string
---@field id? string
---@field identifier table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field nickname? string
---@field physicalAccountID? string
---@field roleIDs? table
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierPhysicalAccountID? string
---@field supplierSepaInstantStatus? string
---@field toDate? string
---@field type? string
---@field usageType? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class AccountUpdateData
---@field id string
---@field accountBalances? table
---@field accountID? string
---@field accountIdentifications? table
---@field accountName? string
---@field accountNames? table
---@field accountSupplierName? string
---@field accountType? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field consolidatedAccountInformation? table
---@field createdBy? table
---@field createdByDisplayName? string
---@field currency? string
---@field defaultPaymentRail? string
---@field description? string
---@field details? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field format? string
---@field fromDate? string
---@field identifier? table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field nickname? string
---@field physicalAccountID? string
---@field roleIDs? table
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierPhysicalAccountID? string
---@field supplierSepaInstantStatus? string
---@field toDate? string
---@field type? string
---@field usageType? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class AccountRemoveMatch
---@field id string

---@class Batch
---@field approveUrl? string
---@field id? string
---@field payouts? table

---@class BatchLoadMatch
---@field id string

---@class BatchCreateData
---@field approveUrl? string
---@field id? string
---@field payouts? table

---@class Beneficiary
---@field approvalCallbackUrl? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field beneficiaries? table
---@field beneficiaryEvents? table
---@field canAuthorise? boolean
---@field canUpdate? boolean
---@field createdBy table
---@field createdByEmailAddress? string
---@field currency string
---@field destination? table
---@field failedBeneficiaries? table
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field isEnabled? boolean
---@field lastAuthorised? string
---@field lastUpdated? string
---@field merchantID? string
---@field name string
---@field nonce? string
---@field sourceAccountIDs? table
---@field sourceAccounts? table
---@field theirReference? string

---@class BeneficiaryLoadMatch
---@field id string
---@field merchant_id? string

---@class BeneficiaryListMatch
---@field approvalCallbackUrl? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field beneficiaries? table
---@field beneficiaryEvents? table
---@field canAuthorise? boolean
---@field canUpdate? boolean
---@field createdBy? table
---@field createdByEmailAddress? string
---@field currency? string
---@field destination? table
---@field failedBeneficiaries? table
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field isEnabled? boolean
---@field lastAuthorised? string
---@field lastUpdated? string
---@field merchantID? string
---@field name? string
---@field nonce? string
---@field sourceAccountIDs? table
---@field sourceAccounts? table
---@field theirReference? string

---@class BeneficiaryCreateData
---@field id string
---@field approvalCallbackUrl? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field beneficiaries? table
---@field beneficiaryEvents? table
---@field canAuthorise? boolean
---@field canUpdate? boolean
---@field createdBy table
---@field createdByEmailAddress? string
---@field currency string
---@field destination? table
---@field failedBeneficiaries? table
---@field hasCurrentUserAuthorised? boolean
---@field inserted? string
---@field isEnabled? boolean
---@field lastAuthorised? string
---@field lastUpdated? string
---@field merchantID? string
---@field name string
---@field nonce? string
---@field sourceAccountIDs? table
---@field sourceAccounts? table
---@field theirReference? string

---@class BeneficiaryUpdateData
---@field id string
---@field approvalCallbackUrl? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field beneficiaries? table
---@field beneficiaryEvents? table
---@field canAuthorise? boolean
---@field canUpdate? boolean
---@field createdBy? table
---@field createdByEmailAddress? string
---@field currency? string
---@field destination? table
---@field failedBeneficiaries? table
---@field hasCurrentUserAuthorised? boolean
---@field inserted? string
---@field isEnabled? boolean
---@field lastAuthorised? string
---@field lastUpdated? string
---@field merchantID? string
---@field name? string
---@field nonce? string
---@field sourceAccountIDs? table
---@field sourceAccounts? table
---@field theirReference? string

---@class BeneficiaryRemoveMatch
---@field id string

---@class BeneficiaryGroup
---@field groupMembers? table
---@field groupName string
---@field id? string
---@field inserted? string
---@field lastUpdated? string
---@field merchantID string

---@class BeneficiaryGroupListMatch
---@field merchant_id string

---@class Card
---@field authorizedAmount? string
---@field currencyCode? string
---@field isPayerAuthenticationRequired? boolean
---@field isSoftDecline? boolean
---@field payerAuthenticationAccessToken? string
---@field payerAuthenticationMerchantData? string
---@field payerAuthenticationUrl? string
---@field payerAuthenticationWindowHeight? number
---@field payerAuthenticationWindowWidth? number
---@field paymentRequestCallbackUrl? string
---@field paymentRequestID? string
---@field requestID? string
---@field responseCode? string
---@field responseType? string
---@field status? string
---@field threeDSRedirectUrl? string
---@field transactionID? string

---@class CardCreateData
---@field paymentrequest_id string
---@field authorizedAmount? string
---@field currencyCode? string
---@field isPayerAuthenticationRequired? boolean
---@field isSoftDecline? boolean
---@field payerAuthenticationAccessToken? string
---@field payerAuthenticationMerchantData? string
---@field payerAuthenticationUrl? string
---@field payerAuthenticationWindowHeight? number
---@field payerAuthenticationWindowWidth? number
---@field paymentRequestCallbackUrl? string
---@field paymentRequestID? string
---@field requestID? string
---@field responseCode? string
---@field responseType? string
---@field status? string
---@field threeDSRedirectUrl? string
---@field transactionID? string

---@class CardCustomerToken
---@field cardType? string
---@field customerEmailAddress? string
---@field expiryMonth? string
---@field expiryYear? string
---@field id? string
---@field inserted? string
---@field lastFourDigits? string
---@field lastUpdated? string
---@field maskedCardNumber? string
---@field merchantID? string
---@field paymentRequestID? string

---@class CardCustomerTokenLoadMatch
---@field customer_email_address string

---@class CardCustomerTokenListMatch
---@field customer_email_address string
---@field merchant_id string

---@class CardCustomerTokenRemoveMatch
---@field id string

---@class CardPayment
---@field authorizedAmount? string
---@field currencyCode? string
---@field isPayerAuthenticationRequired? boolean
---@field isSoftDecline? boolean
---@field payerAuthenticationAccessToken? string
---@field payerAuthenticationMerchantData? string
---@field payerAuthenticationUrl? string
---@field payerAuthenticationWindowHeight? number
---@field payerAuthenticationWindowWidth? number
---@field paymentRequestCallbackUrl? string
---@field paymentRequestID? string
---@field requestID? string
---@field responseCode? string
---@field responseType? string
---@field status? string
---@field threeDSRedirectUrl? string
---@field transactionID? string

---@class CardPaymentCreateData
---@field partial_refund_amount? number
---@field paymentrequest_id string
---@field authorizedAmount? string
---@field currencyCode? string
---@field isPayerAuthenticationRequired? boolean
---@field isSoftDecline? boolean
---@field payerAuthenticationAccessToken? string
---@field payerAuthenticationMerchantData? string
---@field payerAuthenticationUrl? string
---@field payerAuthenticationWindowHeight? number
---@field payerAuthenticationWindowWidth? number
---@field paymentRequestCallbackUrl? string
---@field paymentRequestID? string
---@field requestID? string
---@field responseCode? string
---@field responseType? string
---@field status? string
---@field threeDSRedirectUrl? string
---@field transactionID? string

---@class CardPublicKey
---@field jwt? string

---@class CardPublicKeyLoadMatch
---@field paymentrequest_id string

---@class Consent
---@field authorisationUrl? string
---@field callbackUrl? string
---@field consentID? string
---@field emailAddress? string
---@field expiryDate? string
---@field failureCallbackUrl? string
---@field id? string
---@field inserted? string
---@field institutionID? string
---@field isConnectedAccounts? boolean
---@field isEnabled? boolean
---@field merchantID? string
---@field provider? string
---@field successWebHookUrl? string

---@class ConsentLoadMatch
---@field id string

---@class ConsentListMatch
---@field email string
---@field merchant_id string

---@class ConsentCreateData
---@field authorisationUrl? string
---@field callbackUrl? string
---@field consentID? string
---@field emailAddress? string
---@field expiryDate? string
---@field failureCallbackUrl? string
---@field id? string
---@field inserted? string
---@field institutionID? string
---@field isConnectedAccounts? boolean
---@field isEnabled? boolean
---@field merchantID? string
---@field provider? string
---@field successWebHookUrl? string

---@class ConsentUpdateData
---@field id string
---@field authorisationUrl? string
---@field callbackUrl? string
---@field consentID? string
---@field emailAddress? string
---@field expiryDate? string
---@field failureCallbackUrl? string
---@field inserted? string
---@field institutionID? string
---@field isConnectedAccounts? boolean
---@field isEnabled? boolean
---@field merchantID? string
---@field provider? string
---@field successWebHookUrl? string

---@class ConsentRemoveMatch
---@field id string

---@class Currency
---@field code? string
---@field decimals? number
---@field isFiat? boolean
---@field iso4217AlphaCode? string
---@field iso4217NumericCode? string
---@field symbol? string

---@class CurrencyListMatch
---@field code? string
---@field decimals? number
---@field isFiat? boolean
---@field iso4217AlphaCode? string
---@field iso4217NumericCode? string
---@field symbol? string

---@class DirectDebitBatchSubmit
---@field failedSubmissions? table
---@field successfulSubmissions? table

---@class DirectDebitBatchSubmitCreateData
---@field failedSubmissions? table
---@field successfulSubmissions? table

---@class FxRate
---@field destinationCurrency? string
---@field exchangeRate? number
---@field expiryTime? string
---@field quoteID? string
---@field sourceCurrency? string

---@class FxRateLoadMatch
---@field destination string
---@field source string
---@field valid_for_minute number

---@class FxRateListMatch
---@field destination string
---@field source string

---@class IPayment
---@field paymentRequestID? string
---@field responseType? string

---@class IPaymentCreateData
---@field paymentRequestID? string
---@field responseType? string

---@class Mandate
---@field accountNumber? string
---@field addressLine1 string
---@field addressLine2? string
---@field approvedAt? string
---@field city string
---@field countryCode string
---@field currency? string
---@field customerAccountNumber? string
---@field customerCity? string
---@field customerCountryCode? string
---@field customerCountryName? string
---@field customerEmailAddress? string
---@field customerFirstName? string
---@field customerIban? string
---@field customerLastName? string
---@field customerSortCode? string
---@field emailAddress string
---@field firstName string
---@field iban? string
---@field id? string
---@field inserted? string
---@field isRecurring? boolean
---@field lastName string
---@field lastUpdated? string
---@field merchantID? string
---@field postalCode string
---@field reference? string
---@field sortCode? string
---@field status? string
---@field supplierBankAccountID? string
---@field supplierCustomerID? string
---@field supplierMandateID? string
---@field supplierName? string
---@field supplierStatus? string

---@class MandateLoadMatch
---@field id string

---@class MandateCreateData
---@field accountNumber? string
---@field addressLine1 string
---@field addressLine2? string
---@field approvedAt? string
---@field city string
---@field countryCode string
---@field currency? string
---@field customerAccountNumber? string
---@field customerCity? string
---@field customerCountryCode? string
---@field customerCountryName? string
---@field customerEmailAddress? string
---@field customerFirstName? string
---@field customerIban? string
---@field customerLastName? string
---@field customerSortCode? string
---@field emailAddress string
---@field firstName string
---@field iban? string
---@field id? string
---@field inserted? string
---@field isRecurring? boolean
---@field lastName string
---@field lastUpdated? string
---@field merchantID? string
---@field postalCode string
---@field reference? string
---@field sortCode? string
---@field status? string
---@field supplierBankAccountID? string
---@field supplierCustomerID? string
---@field supplierMandateID? string
---@field supplierName? string
---@field supplierStatus? string

---@class Merchant
---@field accountCurrencies? table
---@field canHaveTrustAccounts? boolean
---@field cardPaymentProcessor? string
---@field companyID? string
---@field displayQrOnHostedPay? boolean
---@field hostedPayVersion? number
---@field id? string
---@field inserted? string
---@field isBlocked? boolean
---@field isExited? boolean
---@field isSuspended? boolean
---@field jurisdiction? string
---@field logoUrlPng? string
---@field logoUrlSvg? string
---@field merchantCategoryCode? string
---@field name? string
---@field notes? string
---@field parentMerchant? table
---@field paymentAccountLimit? number
---@field paymentAccounts? table
---@field reason? string
---@field shortName? string
---@field supportedPaymentMethodsList? table
---@field suspensionReason? string
---@field tags? table
---@field timeZoneId? string
---@field tradingName? string
---@field webHookLimit? number
---@field yourRoleName? string

---@class MerchantLoadMatch
---@field id string

---@class MerchantListMatch
---@field accountCurrencies? table
---@field canHaveTrustAccounts? boolean
---@field cardPaymentProcessor? string
---@field companyID? string
---@field displayQrOnHostedPay? boolean
---@field hostedPayVersion? number
---@field id? string
---@field inserted? string
---@field isBlocked? boolean
---@field isExited? boolean
---@field isSuspended? boolean
---@field jurisdiction? string
---@field logoUrlPng? string
---@field logoUrlSvg? string
---@field merchantCategoryCode? string
---@field name? string
---@field notes? string
---@field parentMerchant? table
---@field paymentAccountLimit? number
---@field paymentAccounts? table
---@field reason? string
---@field shortName? string
---@field supportedPaymentMethodsList? table
---@field suspensionReason? string
---@field tags? table
---@field timeZoneId? string
---@field tradingName? string
---@field webHookLimit? number
---@field yourRoleName? string

---@class MerchantUpdateData
---@field id string
---@field accountCurrencies? table
---@field canHaveTrustAccounts? boolean
---@field cardPaymentProcessor? string
---@field companyID? string
---@field displayQrOnHostedPay? boolean
---@field hostedPayVersion? number
---@field inserted? string
---@field isBlocked? boolean
---@field isExited? boolean
---@field isSuspended? boolean
---@field jurisdiction? string
---@field logoUrlPng? string
---@field logoUrlSvg? string
---@field merchantCategoryCode? string
---@field name? string
---@field notes? string
---@field parentMerchant? table
---@field paymentAccountLimit? number
---@field paymentAccounts? table
---@field reason? string
---@field shortName? string
---@field supportedPaymentMethodsList? table
---@field suspensionReason? string
---@field tags? table
---@field timeZoneId? string
---@field tradingName? string
---@field webHookLimit? number
---@field yourRoleName? string

---@class MerchantRemoveMatch
---@field id string
---@field user_id string

---@class MerchantAuthorisationSetting
---@field amountLower? number
---@field amountUpper? number
---@field authorisationType? string
---@field beneficiariesOnly? boolean
---@field id? string
---@field inserted? string
---@field lastEditorCantAuthorise? boolean
---@field lastUpdated? string
---@field merchantID? string
---@field numberOfAuthorisers? number
---@field roleSettings? table

---@class MerchantAuthorisationSettingListMatch
---@field merchant_id string

---@class MerchantDirectDebitMandatePage
---@field approvedAt? string
---@field currency? string
---@field customerAccountNumber? string
---@field customerCity? string
---@field customerCountryCode? string
---@field customerCountryName? string
---@field customerEmailAddress? string
---@field customerFirstName? string
---@field customerIban? string
---@field customerLastName? string
---@field customerSortCode? string
---@field id? string
---@field inserted? string
---@field isRecurring? boolean
---@field lastUpdated? string
---@field merchantID? string
---@field reference? string
---@field status? string
---@field supplierBankAccountID? string
---@field supplierCustomerID? string
---@field supplierMandateID? string
---@field supplierName? string
---@field supplierStatus? string

---@class MerchantDirectDebitMandatePageListMatch
---@field approvedAt? string
---@field currency? string
---@field customerAccountNumber? string
---@field customerCity? string
---@field customerCountryCode? string
---@field customerCountryName? string
---@field customerEmailAddress? string
---@field customerFirstName? string
---@field customerIban? string
---@field customerLastName? string
---@field customerSortCode? string
---@field id? string
---@field inserted? string
---@field isRecurring? boolean
---@field lastUpdated? string
---@field merchantID? string
---@field reference? string
---@field status? string
---@field supplierBankAccountID? string
---@field supplierCustomerID? string
---@field supplierMandateID? string
---@field supplierName? string
---@field supplierStatus? string

---@class MerchantPayByBankSetting
---@field bankCountryCodes? table
---@field bankID? string
---@field bankName? string
---@field businessInstitutionID? string
---@field currency? string
---@field logo? string
---@field message? string
---@field messageImageUrl? string
---@field order? number
---@field personalInstitutionID? string
---@field processor? string
---@field warningHeading? string
---@field warningMessage? string

---@class MerchantPayByBankSettingListMatch
---@field merchant_id string

---@class MerchantPaymentRequestTemplate
---@field bankPaymentOptions? table
---@field cardPaymentAddressOptions? table
---@field cardPaymentCaptureOptions? table
---@field customFields? table
---@field defaultFields? table
---@field description string
---@field id? string
---@field inserted? string
---@field lastUpdated? string
---@field merchantID? string
---@field name string
---@field notificationOptions? table
---@field paymentMethods? table
---@field paymentTerms? table
---@field priorityBankOptions? table
---@field template table

---@class MerchantPaymentRequestTemplateLoadMatch
---@field id string
---@field paymentrequest_id string

---@class MerchantPaymentRequestTemplateListMatch
---@field merchant_id string

---@class MerchantPaymentRequestTemplateUpdateData
---@field id string
---@field paymentrequest_id string
---@field bankPaymentOptions? table
---@field cardPaymentAddressOptions? table
---@field cardPaymentCaptureOptions? table
---@field customFields? table
---@field defaultFields? table
---@field description? string
---@field inserted? string
---@field lastUpdated? string
---@field merchantID? string
---@field name? string
---@field notificationOptions? table
---@field paymentMethods? table
---@field paymentTerms? table
---@field priorityBankOptions? table
---@field template? table

---@class MerchantPaymentRequestTemplateRemoveMatch
---@field id string
---@field paymentrequest_id string

---@class MerchantToken
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field canAuthorise? boolean
---@field description? string
---@field expiresAt? string
---@field hasCurrentUserAuthorised? boolean
---@field hmacAlgorithm? string
---@field id? string
---@field inserted? string
---@field ipAddressWhitelist? string
---@field isArchived? boolean
---@field isEnabled? boolean
---@field lastAuthorised? string
---@field lastUpdated? string
---@field merchantID? string
---@field nonce string
---@field permissionTypes? table
---@field requestSignatureVersion? number
---@field sharedSecretAlgorithm? string
---@field sharedSecretBase64? string
---@field token? string

---@class MerchantTokenLoadMatch
---@field id string

---@class MerchantTokenListMatch
---@field merchant_id string

---@class MerchantTokenCreateData
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field canAuthorise? boolean
---@field description? string
---@field expiresAt? string
---@field hasCurrentUserAuthorised? boolean
---@field hmacAlgorithm? string
---@field id? string
---@field inserted? string
---@field ipAddressWhitelist? string
---@field isArchived? boolean
---@field isEnabled? boolean
---@field lastAuthorised? string
---@field lastUpdated? string
---@field merchantID? string
---@field nonce string
---@field permissionTypes? table
---@field requestSignatureVersion? number
---@field sharedSecretAlgorithm? string
---@field sharedSecretBase64? string
---@field token? string

---@class MerchantTokenUpdateData
---@field id string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field canAuthorise? boolean
---@field description? string
---@field expiresAt? string
---@field hasCurrentUserAuthorised? boolean
---@field hmacAlgorithm? string
---@field inserted? string
---@field ipAddressWhitelist? string
---@field isArchived? boolean
---@field isEnabled? boolean
---@field lastAuthorised? string
---@field lastUpdated? string
---@field merchantID? string
---@field nonce? string
---@field permissionTypes? table
---@field requestSignatureVersion? number
---@field sharedSecretAlgorithm? string
---@field sharedSecretBase64? string
---@field token? string

---@class Metadata

---@class MetadataLoadMatch

---@class NoFrixionVersion
---@field buildVersion? number
---@field majorVersion? number
---@field minorVersion? number
---@field releaseName? string

---@class NoFrixionVersionLoadMatch
---@field buildVersion? number
---@field majorVersion? number
---@field minorVersion? number
---@field releaseName? string

---@class OpenBanking

---@class OpenBankingCreateData
---@field account_id string

---@class OpenBankingRemoveMatch
---@field account_id string

---@class Payeeverification
---@field accountName string
---@field accountNumber? string
---@field iban string
---@field payeeVerifiedAccountName? string
---@field result? string
---@field secondaryIdentification? string
---@field sortCode? string

---@class PayeeverificationCreateData
---@field accountName string
---@field accountNumber? string
---@field iban string
---@field payeeVerifiedAccountName? string
---@field result? string
---@field secondaryIdentification? string
---@field sortCode? string

---@class Payment
---@field addresses? table
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field autoSendReceipt? boolean
---@field baseOriginUrl? string
---@field callbackUrl? string
---@field cardAuthorizeOnly? boolean
---@field cardCreateToken? boolean
---@field cardCreateTokenMode? string
---@field cardIgnoreCVN? boolean
---@field cardNoPayerAuthentication? boolean
---@field cardProcessorMerchantID? string
---@field cardStripePaymentIntentID? string
---@field cardStripePaymentIntentSecret? string
---@field cardTransmitRawDetails? boolean
---@field createdByUser table
---@field currency? string
---@field customFields? table
---@field customerEmailAddress? string
---@field customerID? string
---@field customerName? string
---@field description? string
---@field destinationAccount? table
---@field directDebitPayment? table
---@field dueDate? string
---@field events? table
---@field failureCallbackUrl? string
---@field fieldDisplaySettings? table
---@field formattedAmount? string
---@field hostedPayCheckoutUrl? string
---@field id? string
---@field ignoreAddressVerification? boolean
---@field inserted? string
---@field insertedSortable? string
---@field isArchived? boolean
---@field jwk? string
---@field lastUpdated? string
---@field lightningInvoice? string
---@field lightningInvoiceExpiresAt? string
---@field merchantDirectDebitMandateID? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field notificationEmailAddresses? string
---@field notificationRoleIDs? table
---@field orderID? string
---@field partialPaymentMethod? string
---@field partialPaymentSteps? string
---@field paymentAttempts? table
---@field paymentMethods? table
---@field paymentProcessor? string
---@field payrunID? string
---@field pispAccountID? string
---@field priorityBankID? string
---@field result? table
---@field sandboxSettleDelayInSeconds? number
---@field shippingAddress? table
---@field shippingAddressCity? string
---@field shippingAddressCountryCode? string
---@field shippingAddressCounty? string
---@field shippingAddressLine1? string
---@field shippingAddressLine2? string
---@field shippingAddressPostCode? string
---@field shippingEmail? string
---@field shippingFirstName? string
---@field shippingLastName? string
---@field shippingPhone? string
---@field status? string
---@field successWebHookUrl? string
---@field tagIds? table
---@field tags? table
---@field title? string
---@field tokenisedCards? table
---@field transactions? table
---@field useHostedPaymentPage? boolean

---@class PaymentLoadMatch
---@field id string

---@class PaymentCreateData
---@field addresses? table
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field autoSendReceipt? boolean
---@field baseOriginUrl? string
---@field callbackUrl? string
---@field cardAuthorizeOnly? boolean
---@field cardCreateToken? boolean
---@field cardCreateTokenMode? string
---@field cardIgnoreCVN? boolean
---@field cardNoPayerAuthentication? boolean
---@field cardProcessorMerchantID? string
---@field cardStripePaymentIntentID? string
---@field cardStripePaymentIntentSecret? string
---@field cardTransmitRawDetails? boolean
---@field createdByUser table
---@field currency? string
---@field customFields? table
---@field customerEmailAddress? string
---@field customerID? string
---@field customerName? string
---@field description? string
---@field destinationAccount? table
---@field directDebitPayment? table
---@field dueDate? string
---@field events? table
---@field failureCallbackUrl? string
---@field fieldDisplaySettings? table
---@field formattedAmount? string
---@field hostedPayCheckoutUrl? string
---@field id? string
---@field ignoreAddressVerification? boolean
---@field inserted? string
---@field insertedSortable? string
---@field isArchived? boolean
---@field jwk? string
---@field lastUpdated? string
---@field lightningInvoice? string
---@field lightningInvoiceExpiresAt? string
---@field merchantDirectDebitMandateID? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field notificationEmailAddresses? string
---@field notificationRoleIDs? table
---@field orderID? string
---@field partialPaymentMethod? string
---@field partialPaymentSteps? string
---@field paymentAttempts? table
---@field paymentMethods? table
---@field paymentProcessor? string
---@field payrunID? string
---@field pispAccountID? string
---@field priorityBankID? string
---@field result? table
---@field sandboxSettleDelayInSeconds? number
---@field shippingAddress? table
---@field shippingAddressCity? string
---@field shippingAddressCountryCode? string
---@field shippingAddressCounty? string
---@field shippingAddressLine1? string
---@field shippingAddressLine2? string
---@field shippingAddressPostCode? string
---@field shippingEmail? string
---@field shippingFirstName? string
---@field shippingLastName? string
---@field shippingPhone? string
---@field status? string
---@field successWebHookUrl? string
---@field tagIds? table
---@field tags? table
---@field title? string
---@field tokenisedCards? table
---@field transactions? table
---@field useHostedPaymentPage? boolean

---@class PaymentUpdateData
---@field id string
---@field addresses? table
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field autoSendReceipt? boolean
---@field baseOriginUrl? string
---@field callbackUrl? string
---@field cardAuthorizeOnly? boolean
---@field cardCreateToken? boolean
---@field cardCreateTokenMode? string
---@field cardIgnoreCVN? boolean
---@field cardNoPayerAuthentication? boolean
---@field cardProcessorMerchantID? string
---@field cardStripePaymentIntentID? string
---@field cardStripePaymentIntentSecret? string
---@field cardTransmitRawDetails? boolean
---@field createdByUser? table
---@field currency? string
---@field customFields? table
---@field customerEmailAddress? string
---@field customerID? string
---@field customerName? string
---@field description? string
---@field destinationAccount? table
---@field directDebitPayment? table
---@field dueDate? string
---@field events? table
---@field failureCallbackUrl? string
---@field fieldDisplaySettings? table
---@field formattedAmount? string
---@field hostedPayCheckoutUrl? string
---@field ignoreAddressVerification? boolean
---@field inserted? string
---@field insertedSortable? string
---@field isArchived? boolean
---@field jwk? string
---@field lastUpdated? string
---@field lightningInvoice? string
---@field lightningInvoiceExpiresAt? string
---@field merchantDirectDebitMandateID? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field notificationEmailAddresses? string
---@field notificationRoleIDs? table
---@field orderID? string
---@field partialPaymentMethod? string
---@field partialPaymentSteps? string
---@field paymentAttempts? table
---@field paymentMethods? table
---@field paymentProcessor? string
---@field payrunID? string
---@field pispAccountID? string
---@field priorityBankID? string
---@field result? table
---@field sandboxSettleDelayInSeconds? number
---@field shippingAddress? table
---@field shippingAddressCity? string
---@field shippingAddressCountryCode? string
---@field shippingAddressCounty? string
---@field shippingAddressLine1? string
---@field shippingAddressLine2? string
---@field shippingAddressPostCode? string
---@field shippingEmail? string
---@field shippingFirstName? string
---@field shippingLastName? string
---@field shippingPhone? string
---@field status? string
---@field successWebHookUrl? string
---@field tagIds? table
---@field tags? table
---@field title? string
---@field tokenisedCards? table
---@field transactions? table
---@field useHostedPaymentPage? boolean

---@class PaymentAccount
---@field accountName? string
---@field accountSupplierName? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field createdBy table
---@field createdByDisplayName? string
---@field currency? string
---@field defaultPaymentRail? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field id? string
---@field identifier table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field physicalAccountID? string
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierSepaInstantStatus? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class PaymentAccountListMatch
---@field accountName? string
---@field accountSupplierName? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field createdBy? table
---@field createdByDisplayName? string
---@field currency? string
---@field defaultPaymentRail? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field id? string
---@field identifier? table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field physicalAccountID? string
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierSepaInstantStatus? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class PaymentAccountMinimal
---@field accountName? string
---@field availableBalance? number
---@field balance? number
---@field balanceMinorUnits? number
---@field currency? string
---@field id? string
---@field identifier table
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field merchantID? string
---@field submittedPayoutsBalance? number

---@class PaymentAccountMinimalListMatch
---@field accountName? string
---@field availableBalance? number
---@field balance? number
---@field balanceMinorUnits? number
---@field currency? string
---@field id? string
---@field identifier? table
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field merchantID? string
---@field submittedPayoutsBalance? number

---@class PaymentInitiation
---@field paymentInitiationID? string
---@field paymentRequestCallbackUrl? string
---@field paymentRequestID? string
---@field redirectUrl? string
---@field responseType? string
---@field specificErrorMessage? string

---@class PaymentInitiationCreateData
---@field paymentrequest_id string
---@field paymentInitiationID? string
---@field paymentRequestCallbackUrl? string
---@field paymentRequestID? string
---@field redirectUrl? string
---@field responseType? string
---@field specificErrorMessage? string

---@class PaymentRequest
---@field addresses? table
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field autoSendReceipt? boolean
---@field baseOriginUrl? string
---@field callbackUrl? string
---@field cardAuthorizeOnly? boolean
---@field cardCreateToken? boolean
---@field cardCreateTokenMode? string
---@field cardIgnoreCVN? boolean
---@field cardProcessorMerchantID? string
---@field cardStripePaymentIntentID? string
---@field cardStripePaymentIntentSecret? string
---@field createdByUser table
---@field currency? string
---@field customFields? table
---@field customerEmailAddress? string
---@field customerID? string
---@field customerName? string
---@field description? string
---@field destinationAccount? table
---@field directDebitPayment? table
---@field doSimulateSettlementFailure? boolean
---@field dueDate? string
---@field errorDescription? string
---@field events? table
---@field failedPaymentRequests? table
---@field failureCallbackUrl? string
---@field fieldDisplaySettings? table
---@field formattedAmount? string
---@field hostedPayCheckoutUrl? string
---@field id? string
---@field ignoreAddressVerification? boolean
---@field inserted? string
---@field insertedSortable? string
---@field institution? string
---@field isArchived? boolean
---@field jwk? string
---@field lastUpdated? string
---@field lightningInvoice? string
---@field lightningInvoiceExpiresAt? string
---@field merchantDirectDebitMandateID? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field notificationEmailAddresses? string
---@field notificationRoleIDs? table
---@field orderID? string
---@field partialPaymentMethod? string
---@field partialPaymentSteps? string
---@field paymentAttempts? table
---@field paymentInitiationID? string
---@field paymentMethods? table
---@field paymentProcessor? string
---@field paymentRequests? table
---@field payrunID? string
---@field pispAccountID? string
---@field priorityBankID? string
---@field result? table
---@field sandboxSettleDelayInSeconds? number
---@field shippingAddress? table
---@field status? string
---@field successWebHookUrl? string
---@field tags? table
---@field title? string
---@field tokenisedCards? table
---@field transactions? table
---@field useHostedPaymentPage? boolean

---@class PaymentRequestLoadMatch
---@field addresses? table
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field autoSendReceipt? boolean
---@field baseOriginUrl? string
---@field callbackUrl? string
---@field cardAuthorizeOnly? boolean
---@field cardCreateToken? boolean
---@field cardCreateTokenMode? string
---@field cardIgnoreCVN? boolean
---@field cardProcessorMerchantID? string
---@field cardStripePaymentIntentID? string
---@field cardStripePaymentIntentSecret? string
---@field createdByUser? table
---@field currency? string
---@field customFields? table
---@field customerEmailAddress? string
---@field customerID? string
---@field customerName? string
---@field description? string
---@field destinationAccount? table
---@field directDebitPayment? table
---@field doSimulateSettlementFailure? boolean
---@field dueDate? string
---@field errorDescription? string
---@field events? table
---@field failedPaymentRequests? table
---@field failureCallbackUrl? string
---@field fieldDisplaySettings? table
---@field formattedAmount? string
---@field hostedPayCheckoutUrl? string
---@field id string
---@field ignoreAddressVerification? boolean
---@field inserted? string
---@field insertedSortable? string
---@field institution? string
---@field isArchived? boolean
---@field jwk? string
---@field lastUpdated? string
---@field lightningInvoice? string
---@field lightningInvoiceExpiresAt? string
---@field merchantDirectDebitMandateID? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field notificationEmailAddresses? string
---@field notificationRoleIDs? table
---@field orderID? string
---@field partialPaymentMethod? string
---@field partialPaymentSteps? string
---@field paymentAttempts? table
---@field paymentInitiationID? string
---@field paymentMethods? table
---@field paymentProcessor? string
---@field paymentRequests? table
---@field payrunID? string
---@field pispAccountID? string
---@field priorityBankID? string
---@field result? table
---@field sandboxSettleDelayInSeconds? number
---@field shippingAddress? table
---@field status? string
---@field successWebHookUrl? string
---@field tags? table
---@field title? string
---@field tokenisedCards? table
---@field transactions? table
---@field useHostedPaymentPage? boolean

---@class PaymentRequestListMatch
---@field addresses? table
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field autoSendReceipt? boolean
---@field baseOriginUrl? string
---@field callbackUrl? string
---@field cardAuthorizeOnly? boolean
---@field cardCreateToken? boolean
---@field cardCreateTokenMode? string
---@field cardIgnoreCVN? boolean
---@field cardProcessorMerchantID? string
---@field cardStripePaymentIntentID? string
---@field cardStripePaymentIntentSecret? string
---@field createdByUser? table
---@field currency? string
---@field customFields? table
---@field customerEmailAddress? string
---@field customerID? string
---@field customerName? string
---@field description? string
---@field destinationAccount? table
---@field directDebitPayment? table
---@field doSimulateSettlementFailure? boolean
---@field dueDate? string
---@field errorDescription? string
---@field events? table
---@field failedPaymentRequests? table
---@field failureCallbackUrl? string
---@field fieldDisplaySettings? table
---@field formattedAmount? string
---@field hostedPayCheckoutUrl? string
---@field id? string
---@field ignoreAddressVerification? boolean
---@field inserted? string
---@field insertedSortable? string
---@field institution? string
---@field isArchived? boolean
---@field jwk? string
---@field lastUpdated? string
---@field lightningInvoice? string
---@field lightningInvoiceExpiresAt? string
---@field merchantDirectDebitMandateID? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field notificationEmailAddresses? string
---@field notificationRoleIDs? table
---@field orderID? string
---@field partialPaymentMethod? string
---@field partialPaymentSteps? string
---@field paymentAttempts? table
---@field paymentInitiationID? string
---@field paymentMethods? table
---@field paymentProcessor? string
---@field paymentRequests? table
---@field payrunID? string
---@field pispAccountID? string
---@field priorityBankID? string
---@field result? table
---@field sandboxSettleDelayInSeconds? number
---@field shippingAddress? table
---@field status? string
---@field successWebHookUrl? string
---@field tags? table
---@field title? string
---@field tokenisedCards? table
---@field transactions? table
---@field useHostedPaymentPage? boolean

---@class PaymentRequestCreateData
---@field addresses? table
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field autoSendReceipt? boolean
---@field baseOriginUrl? string
---@field callbackUrl? string
---@field cardAuthorizeOnly? boolean
---@field cardCreateToken? boolean
---@field cardCreateTokenMode? string
---@field cardIgnoreCVN? boolean
---@field cardProcessorMerchantID? string
---@field cardStripePaymentIntentID? string
---@field cardStripePaymentIntentSecret? string
---@field createdByUser table
---@field currency? string
---@field customFields? table
---@field customerEmailAddress? string
---@field customerID? string
---@field customerName? string
---@field description? string
---@field destinationAccount? table
---@field directDebitPayment? table
---@field doSimulateSettlementFailure? boolean
---@field dueDate? string
---@field errorDescription? string
---@field events? table
---@field failedPaymentRequests? table
---@field failureCallbackUrl? string
---@field fieldDisplaySettings? table
---@field formattedAmount? string
---@field hostedPayCheckoutUrl? string
---@field id? string
---@field ignoreAddressVerification? boolean
---@field inserted? string
---@field insertedSortable? string
---@field institution? string
---@field isArchived? boolean
---@field jwk? string
---@field lastUpdated? string
---@field lightningInvoice? string
---@field lightningInvoiceExpiresAt? string
---@field merchantDirectDebitMandateID? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field notificationEmailAddresses? string
---@field notificationRoleIDs? table
---@field orderID? string
---@field partialPaymentMethod? string
---@field partialPaymentSteps? string
---@field paymentAttempts? table
---@field paymentInitiationID? string
---@field paymentMethods? table
---@field paymentProcessor? string
---@field paymentRequests? table
---@field payrunID? string
---@field pispAccountID? string
---@field priorityBankID? string
---@field result? table
---@field sandboxSettleDelayInSeconds? number
---@field shippingAddress? table
---@field status? string
---@field successWebHookUrl? string
---@field tags? table
---@field title? string
---@field tokenisedCards? table
---@field transactions? table
---@field useHostedPaymentPage? boolean

---@class PaymentRequestUpdateData
---@field paymentrequest_id string
---@field addresses? table
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field autoSendReceipt? boolean
---@field baseOriginUrl? string
---@field callbackUrl? string
---@field cardAuthorizeOnly? boolean
---@field cardCreateToken? boolean
---@field cardCreateTokenMode? string
---@field cardIgnoreCVN? boolean
---@field cardProcessorMerchantID? string
---@field cardStripePaymentIntentID? string
---@field cardStripePaymentIntentSecret? string
---@field createdByUser? table
---@field currency? string
---@field customFields? table
---@field customerEmailAddress? string
---@field customerID? string
---@field customerName? string
---@field description? string
---@field destinationAccount? table
---@field directDebitPayment? table
---@field doSimulateSettlementFailure? boolean
---@field dueDate? string
---@field errorDescription? string
---@field events? table
---@field failedPaymentRequests? table
---@field failureCallbackUrl? string
---@field fieldDisplaySettings? table
---@field formattedAmount? string
---@field hostedPayCheckoutUrl? string
---@field id? string
---@field ignoreAddressVerification? boolean
---@field inserted? string
---@field insertedSortable? string
---@field institution? string
---@field isArchived? boolean
---@field jwk? string
---@field lastUpdated? string
---@field lightningInvoice? string
---@field lightningInvoiceExpiresAt? string
---@field merchantDirectDebitMandateID? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field notificationEmailAddresses? string
---@field notificationRoleIDs? table
---@field orderID? string
---@field partialPaymentMethod? string
---@field partialPaymentSteps? string
---@field paymentAttempts? table
---@field paymentInitiationID? string
---@field paymentMethods? table
---@field paymentProcessor? string
---@field paymentRequests? table
---@field payrunID? string
---@field pispAccountID? string
---@field priorityBankID? string
---@field result? table
---@field sandboxSettleDelayInSeconds? number
---@field shippingAddress? table
---@field status? string
---@field successWebHookUrl? string
---@field tags? table
---@field title? string
---@field tokenisedCards? table
---@field transactions? table
---@field useHostedPaymentPage? boolean

---@class PaymentRequestRemoveMatch
---@field id string

---@class PaymentRequestEvent
---@field amount number
---@field applePayTransactionID? string
---@field cardAuthorizationResponseID? string
---@field cardExpiryMonth? number
---@field cardExpiryYear? number
---@field cardIssuer? string
---@field cardIssuerCountry? string
---@field cardLastFourDigits? string
---@field cardRequestID? string
---@field cardScheme? string
---@field cardTokenCustomerID? string
---@field cardTransactionID? string
---@field currency? string
---@field directDebitPaymentID? string
---@field directDebitPaymentReference? string
---@field drirectDebitMandateID? string
---@field errorMessage? string
---@field errorReason? string
---@field eventType? string
---@field id? string
---@field inserted? string
---@field lightningInvoice? string
---@field lightningRHash? string
---@field originUrl? string
---@field paymentMethodType? string
---@field paymentProcessorName? string
---@field paymentRequestID? string
---@field pispBankStatus? string
---@field pispPaymentInitiationID? string
---@field pispPaymentInstitutionName? string
---@field pispPaymentServiceProviderID? string
---@field pispRedirectUrl? string
---@field reconciledTransactionID? string
---@field refundPayoutID? string
---@field status? string
---@field walletName? string

---@class PaymentRequestEventListMatch
---@field paymentrequest_id string

---@class PaymentRequestMetric

---@class PaymentRequestMetricLoadMatch

---@class PaymentRequestMinimal
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field callbackUrl? string
---@field cardStripePaymentIntentSecret? string
---@field countryCode? string
---@field currency? string
---@field customFieldsToDisplay? table
---@field description? string
---@field dueDate? string
---@field fieldDisplaySettings? table
---@field googlePayMerchantID? string
---@field id? string
---@field jwk? string
---@field merchantID? string
---@field merchantLogoUrlPng? string
---@field merchantLogoUrlSvg? string
---@field merchantName? string
---@field merchantShortName? string
---@field partialPaymentMethod? string
---@field paymentAttempts? table
---@field paymentMethodsList? table
---@field paymentProcessor? string
---@field paymentProcessorKey? string
---@field pispError? string
---@field priorityBankID? string
---@field status? string
---@field stripeAccountID? string
---@field title? string

---@class PaymentRequestMinimalListMatch
---@field paymentrequest_id string

---@class PaymentRequestResult
---@field amount? number
---@field amountPending? number
---@field amountReceived? number
---@field amountRefunded? number
---@field currency? string
---@field customerID? string
---@field paymentRequestID? string
---@field payments? table
---@field pispAuthorizations? table
---@field requestedAmount? number
---@field result? string

---@class PaymentRequestResultListMatch
---@field paymentrequest_id string

---@class Payout
---@field accountID? string
---@field allowIncomplete? boolean
---@field amount? number
---@field amountMinorUnits? number
---@field approvePayoutUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field beneficiary table
---@field beneficiaryID? string
---@field canAuthorise? boolean
---@field canProcess? boolean
---@field canUpdate? boolean
---@field chargeBearer? string
---@field createdBy? string
---@field createdByEmailAddress? string
---@field currency? string
---@field currentUserID? string
---@field description? string
---@field destination? table
---@field documents? table
---@field events? table
---@field failedPayouts? table
---@field formattedAmount? string
---@field formattedFxDestinationAmount? string
---@field formattedSchedule? string
---@field formattedScheduleDayOnly? string
---@field formattedSourceAccountAvailableBalance? string
---@field fxDestinationAmount? number
---@field fxDestinationAmountMinorUnits? number
---@field fxDestinationCurrency? string
---@field fxQuoteExpiresAt? string
---@field fxQuoteID? string
---@field fxRate? number
---@field fxUseDestinationAmount? boolean
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field invoiceID? string
---@field isArchived? boolean
---@field isFailed? boolean
---@field isSettled? boolean
---@field isSubmitted? boolean
---@field lastUpdated? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field nonce? string
---@field paymentProcessor? string
---@field paymentRail? string
---@field payouts? table
---@field payrunID? string
---@field payrunName? string
---@field reason? string
---@field rule? table
---@field scheduleDate? string
---@field scheduled? boolean
---@field sourceAccountAvailableBalance? number
---@field sourceAccountAvailableBalanceMinorUnits? number
---@field sourceAccountBic? string
---@field sourceAccountCurrency? string
---@field sourceAccountIban? string
---@field sourceAccountIdentifier table
---@field sourceAccountName? string
---@field sourceAccountNumber? string
---@field sourceAccountSortcode? string
---@field status? string
---@field tagIds? table
---@field tags? table
---@field theirReference? string
---@field topupPayrunID? string
---@field transactedAmount? number
---@field transactedFxAmount? number
---@field transactedFxRate? number
---@field type? string
---@field userID? string
---@field yourReference? string

---@class PayoutLoadMatch
---@field id string

---@class PayoutListMatch
---@field accountID? string
---@field allowIncomplete? boolean
---@field amount? number
---@field amountMinorUnits? number
---@field approvePayoutUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field beneficiary? table
---@field beneficiaryID? string
---@field canAuthorise? boolean
---@field canProcess? boolean
---@field canUpdate? boolean
---@field chargeBearer? string
---@field createdBy? string
---@field createdByEmailAddress? string
---@field currency? string
---@field currentUserID? string
---@field description? string
---@field destination? table
---@field documents? table
---@field events? table
---@field failedPayouts? table
---@field formattedAmount? string
---@field formattedFxDestinationAmount? string
---@field formattedSchedule? string
---@field formattedScheduleDayOnly? string
---@field formattedSourceAccountAvailableBalance? string
---@field fxDestinationAmount? number
---@field fxDestinationAmountMinorUnits? number
---@field fxDestinationCurrency? string
---@field fxQuoteExpiresAt? string
---@field fxQuoteID? string
---@field fxRate? number
---@field fxUseDestinationAmount? boolean
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field invoiceID? string
---@field isArchived? boolean
---@field isFailed? boolean
---@field isSettled? boolean
---@field isSubmitted? boolean
---@field lastUpdated? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field nonce? string
---@field paymentProcessor? string
---@field paymentRail? string
---@field payouts? table
---@field payrunID? string
---@field payrunName? string
---@field reason? string
---@field rule? table
---@field scheduleDate? string
---@field scheduled? boolean
---@field sourceAccountAvailableBalance? number
---@field sourceAccountAvailableBalanceMinorUnits? number
---@field sourceAccountBic? string
---@field sourceAccountCurrency? string
---@field sourceAccountIban? string
---@field sourceAccountIdentifier? table
---@field sourceAccountName? string
---@field sourceAccountNumber? string
---@field sourceAccountSortcode? string
---@field status? string
---@field tagIds? table
---@field tags? table
---@field theirReference? string
---@field topupPayrunID? string
---@field transactedAmount? number
---@field transactedFxAmount? number
---@field transactedFxRate? number
---@field type? string
---@field userID? string
---@field yourReference? string

---@class PayoutCreateData
---@field id string
---@field accountID? string
---@field allowIncomplete? boolean
---@field amount? number
---@field amountMinorUnits? number
---@field approvePayoutUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field beneficiary table
---@field beneficiaryID? string
---@field canAuthorise? boolean
---@field canProcess? boolean
---@field canUpdate? boolean
---@field chargeBearer? string
---@field createdBy? string
---@field createdByEmailAddress? string
---@field currency? string
---@field currentUserID? string
---@field description? string
---@field destination? table
---@field documents? table
---@field events? table
---@field failedPayouts? table
---@field formattedAmount? string
---@field formattedFxDestinationAmount? string
---@field formattedSchedule? string
---@field formattedScheduleDayOnly? string
---@field formattedSourceAccountAvailableBalance? string
---@field fxDestinationAmount? number
---@field fxDestinationAmountMinorUnits? number
---@field fxDestinationCurrency? string
---@field fxQuoteExpiresAt? string
---@field fxQuoteID? string
---@field fxRate? number
---@field fxUseDestinationAmount? boolean
---@field hasCurrentUserAuthorised? boolean
---@field inserted? string
---@field invoiceID? string
---@field isArchived? boolean
---@field isFailed? boolean
---@field isSettled? boolean
---@field isSubmitted? boolean
---@field lastUpdated? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field nonce? string
---@field paymentProcessor? string
---@field paymentRail? string
---@field payouts? table
---@field payrunID? string
---@field payrunName? string
---@field reason? string
---@field rule? table
---@field scheduleDate? string
---@field scheduled? boolean
---@field sourceAccountAvailableBalance? number
---@field sourceAccountAvailableBalanceMinorUnits? number
---@field sourceAccountBic? string
---@field sourceAccountCurrency? string
---@field sourceAccountIban? string
---@field sourceAccountIdentifier table
---@field sourceAccountName? string
---@field sourceAccountNumber? string
---@field sourceAccountSortcode? string
---@field status? string
---@field tagIds? table
---@field tags? table
---@field theirReference? string
---@field topupPayrunID? string
---@field transactedAmount? number
---@field transactedFxAmount? number
---@field transactedFxRate? number
---@field type? string
---@field userID? string
---@field yourReference? string

---@class PayoutUpdateData
---@field id string
---@field accountID? string
---@field allowIncomplete? boolean
---@field amount? number
---@field amountMinorUnits? number
---@field approvePayoutUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field beneficiary? table
---@field beneficiaryID? string
---@field canAuthorise? boolean
---@field canProcess? boolean
---@field canUpdate? boolean
---@field chargeBearer? string
---@field createdBy? string
---@field createdByEmailAddress? string
---@field currency? string
---@field currentUserID? string
---@field description? string
---@field destination? table
---@field documents? table
---@field events? table
---@field failedPayouts? table
---@field formattedAmount? string
---@field formattedFxDestinationAmount? string
---@field formattedSchedule? string
---@field formattedScheduleDayOnly? string
---@field formattedSourceAccountAvailableBalance? string
---@field fxDestinationAmount? number
---@field fxDestinationAmountMinorUnits? number
---@field fxDestinationCurrency? string
---@field fxQuoteExpiresAt? string
---@field fxQuoteID? string
---@field fxRate? number
---@field fxUseDestinationAmount? boolean
---@field hasCurrentUserAuthorised? boolean
---@field inserted? string
---@field invoiceID? string
---@field isArchived? boolean
---@field isFailed? boolean
---@field isSettled? boolean
---@field isSubmitted? boolean
---@field lastUpdated? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field nonce? string
---@field paymentProcessor? string
---@field paymentRail? string
---@field payouts? table
---@field payrunID? string
---@field payrunName? string
---@field reason? string
---@field rule? table
---@field scheduleDate? string
---@field scheduled? boolean
---@field sourceAccountAvailableBalance? number
---@field sourceAccountAvailableBalanceMinorUnits? number
---@field sourceAccountBic? string
---@field sourceAccountCurrency? string
---@field sourceAccountIban? string
---@field sourceAccountIdentifier? table
---@field sourceAccountName? string
---@field sourceAccountNumber? string
---@field sourceAccountSortcode? string
---@field status? string
---@field tagIds? table
---@field tags? table
---@field theirReference? string
---@field topupPayrunID? string
---@field transactedAmount? number
---@field transactedFxAmount? number
---@field transactedFxRate? number
---@field type? string
---@field userID? string
---@field yourReference? string

---@class PayoutRemoveMatch
---@field id string

---@class PayoutKeysetPage
---@field accountID? string
---@field amount? number
---@field amountMinorUnits? number
---@field approvePayoutUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field beneficiary table
---@field canAuthorise? boolean
---@field canProcess? boolean
---@field canUpdate? boolean
---@field chargeBearer? string
---@field createdBy? string
---@field createdByEmailAddress? string
---@field currency? string
---@field currentUserID? string
---@field description? string
---@field destination? table
---@field documents? table
---@field events? table
---@field formattedAmount? string
---@field formattedFxDestinationAmount? string
---@field formattedSchedule? string
---@field formattedScheduleDayOnly? string
---@field formattedSourceAccountAvailableBalance? string
---@field fxDestinationAmount? number
---@field fxDestinationAmountMinorUnits? number
---@field fxDestinationCurrency? string
---@field fxQuoteExpiresAt? string
---@field fxQuoteID? string
---@field fxRate? number
---@field fxUseDestinationAmount? boolean
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field invoiceID? string
---@field isArchived? boolean
---@field isFailed? boolean
---@field isSettled? boolean
---@field isSubmitted? boolean
---@field lastUpdated? string
---@field merchantID? string
---@field merchantTokenDescription? string
---@field nonce? string
---@field paymentProcessor? string
---@field paymentRail? string
---@field payrunID? string
---@field payrunName? string
---@field rule? table
---@field scheduleDate? string
---@field scheduled? boolean
---@field sourceAccountAvailableBalance? number
---@field sourceAccountAvailableBalanceMinorUnits? number
---@field sourceAccountBic? string
---@field sourceAccountCurrency? string
---@field sourceAccountIban? string
---@field sourceAccountIdentifier table
---@field sourceAccountName? string
---@field sourceAccountNumber? string
---@field sourceAccountSortcode? string
---@field status? string
---@field tags? table
---@field theirReference? string
---@field topupPayrunID? string
---@field transactedAmount? number
---@field transactedFxAmount? number
---@field transactedFxRate? number
---@field type? string
---@field userID? string
---@field yourReference? string

---@class PayoutKeysetPageListMatch
---@field merchant_id string

---@class PayoutMetric

---@class PayoutMetricLoadMatch

---@class Payrun
---@field authorisationDate? string
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field canAuthorise? boolean
---@field canDelete? boolean
---@field canEdit? boolean
---@field events? table
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field invoices? table
---@field invoicesMinimal? table
---@field isArchived? boolean
---@field lastUpdated? string
---@field lastUpdatedBy table
---@field merchantID? string
---@field name? string
---@field nonce? string
---@field notes? string
---@field payments? table
---@field payouts? table
---@field payoutsCount? number
---@field reason? string
---@field scheduleDate? string
---@field scheduledDate? string
---@field sourceAccounts? table
---@field status? string
---@field totalEur? number
---@field totalGbp? number
---@field totalUsd? number

---@class PayrunLoadMatch
---@field id string

---@class PayrunListMatch
---@field authorisationDate? string
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field canAuthorise? boolean
---@field canDelete? boolean
---@field canEdit? boolean
---@field events? table
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field invoices? table
---@field invoicesMinimal? table
---@field isArchived? boolean
---@field lastUpdated? string
---@field lastUpdatedBy? table
---@field merchantID? string
---@field name? string
---@field nonce? string
---@field notes? string
---@field payments? table
---@field payouts? table
---@field payoutsCount? number
---@field reason? string
---@field scheduleDate? string
---@field scheduledDate? string
---@field sourceAccounts? table
---@field status? string
---@field totalEur? number
---@field totalGbp? number
---@field totalUsd? number

---@class PayrunCreateData
---@field id string
---@field authorisationDate? string
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field canAuthorise? boolean
---@field canDelete? boolean
---@field canEdit? boolean
---@field events? table
---@field hasCurrentUserAuthorised? boolean
---@field inserted? string
---@field invoices? table
---@field invoicesMinimal? table
---@field isArchived? boolean
---@field lastUpdated? string
---@field lastUpdatedBy table
---@field merchantID? string
---@field name? string
---@field nonce? string
---@field notes? string
---@field payments? table
---@field payouts? table
---@field payoutsCount? number
---@field reason? string
---@field scheduleDate? string
---@field scheduledDate? string
---@field sourceAccounts? table
---@field status? string
---@field totalEur? number
---@field totalGbp? number
---@field totalUsd? number

---@class PayrunUpdateData
---@field id string
---@field authorisationDate? string
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field batchPayoutID? string
---@field canAuthorise? boolean
---@field canDelete? boolean
---@field canEdit? boolean
---@field events? table
---@field hasCurrentUserAuthorised? boolean
---@field inserted? string
---@field invoices? table
---@field invoicesMinimal? table
---@field isArchived? boolean
---@field lastUpdated? string
---@field lastUpdatedBy? table
---@field merchantID? string
---@field name? string
---@field nonce? string
---@field notes? string
---@field payments? table
---@field payouts? table
---@field payoutsCount? number
---@field reason? string
---@field scheduleDate? string
---@field scheduledDate? string
---@field sourceAccounts? table
---@field status? string
---@field totalEur? number
---@field totalGbp? number
---@field totalUsd? number

---@class PayrunRemoveMatch
---@field id string

---@class Report

---@class ReportUpdateData
---@field id string

---@class ReportResult
---@field contentType? string
---@field contents? string
---@field lastCompletedAt? string
---@field merchantID? string
---@field reportName? string
---@field reportType? string
---@field statementNumber? number

---@class ReportResultLoadMatch
---@field id number
---@field report_id string

---@class Role
---@field failedRoles? table
---@field roles? table

---@class RoleCreateData
---@field merchant_id string
---@field failedRoles? table
---@field roles? table

---@class Rule
---@field account? table
---@field accountID? string
---@field approveUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field canAuthorise? boolean
---@field createdBy table
---@field description? string
---@field endAt? string
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field isDisabled? boolean
---@field lastExecutedAt? string
---@field lastRunAtTransactionDate? string
---@field lastUpdated? string
---@field merchantID? string
---@field name? string
---@field nonce string
---@field onApprovedWebHookUrl? string
---@field onExecutionErrorWebHookUrl? string
---@field onExecutionSuccessWebHookUrl? string
---@field startAt? string
---@field status? string
---@field sweepAction? table
---@field timeZoneId? string
---@field triggerCronExpression? string
---@field triggerOnPayIn? boolean
---@field userID? string
---@field webHookSecret? string

---@class RuleLoadMatch
---@field id string

---@class RuleListMatch
---@field account? table
---@field accountID? string
---@field approveUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field canAuthorise? boolean
---@field createdBy? table
---@field description? string
---@field endAt? string
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field isDisabled? boolean
---@field lastExecutedAt? string
---@field lastRunAtTransactionDate? string
---@field lastUpdated? string
---@field merchantID? string
---@field name? string
---@field nonce? string
---@field onApprovedWebHookUrl? string
---@field onExecutionErrorWebHookUrl? string
---@field onExecutionSuccessWebHookUrl? string
---@field startAt? string
---@field status? string
---@field sweepAction? table
---@field timeZoneId? string
---@field triggerCronExpression? string
---@field triggerOnPayIn? boolean
---@field userID? string
---@field webHookSecret? string

---@class RuleCreateData
---@field account? table
---@field accountID? string
---@field approveUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field canAuthorise? boolean
---@field createdBy table
---@field description? string
---@field endAt? string
---@field hasCurrentUserAuthorised? boolean
---@field id? string
---@field inserted? string
---@field isDisabled? boolean
---@field lastExecutedAt? string
---@field lastRunAtTransactionDate? string
---@field lastUpdated? string
---@field merchantID? string
---@field name? string
---@field nonce string
---@field onApprovedWebHookUrl? string
---@field onExecutionErrorWebHookUrl? string
---@field onExecutionSuccessWebHookUrl? string
---@field startAt? string
---@field status? string
---@field sweepAction? table
---@field timeZoneId? string
---@field triggerCronExpression? string
---@field triggerOnPayIn? boolean
---@field userID? string
---@field webHookSecret? string

---@class RuleUpdateData
---@field id string
---@field account? table
---@field accountID? string
---@field approveUrl? string
---@field approverID? string
---@field authenticationMethods? table
---@field authorisations? table
---@field authorisersCompletedCount? number
---@field authorisersRequiredCount? number
---@field canAuthorise? boolean
---@field createdBy? table
---@field description? string
---@field endAt? string
---@field hasCurrentUserAuthorised? boolean
---@field inserted? string
---@field isDisabled? boolean
---@field lastExecutedAt? string
---@field lastRunAtTransactionDate? string
---@field lastUpdated? string
---@field merchantID? string
---@field name? string
---@field nonce? string
---@field onApprovedWebHookUrl? string
---@field onExecutionErrorWebHookUrl? string
---@field onExecutionSuccessWebHookUrl? string
---@field startAt? string
---@field status? string
---@field sweepAction? table
---@field timeZoneId? string
---@field triggerCronExpression? string
---@field triggerOnPayIn? boolean
---@field userID? string
---@field webHookSecret? string

---@class RuleRemoveMatch
---@field id string

---@class RuleEvent
---@field errorMessage? string
---@field id? string
---@field inserted? string
---@field isAuthoriseToEnable? boolean
---@field message? string
---@field rawResponse? string
---@field ruleEventType? string
---@field ruleID? string
---@field user table

---@class RuleEventListMatch
---@field id string

---@class Tag
---@field colourHex? string
---@field description? string
---@field id? string
---@field merchantID string
---@field name string

---@class TagListMatch
---@field merchant_id string

---@class TagCreateData
---@field merchant_id string
---@field colourHex? string
---@field description? string
---@field id? string
---@field merchantID string
---@field name string

---@class Token

---@class TokenCreateData
---@field id string

---@class TokenRemoveMatch
---@field id string

---@class Transaction
---@field accountID? string
---@field accountName? string
---@field accountSequenceNumber? number
---@field addressDetails? table
---@field amount? number
---@field amountMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bookingDateTime? string
---@field chargeDetails? table
---@field content? table
---@field counterparty? table
---@field counterpartySummary? string
---@field currency? string
---@field currencyExchange? table
---@field date? string
---@field description? string
---@field enrichment? table
---@field fxAmount? number
---@field fxCurrency? string
---@field fxRate? number
---@field grossAmount table
---@field id? string
---@field inserted? string
---@field isoBankTransactionCode? table
---@field merchant? table
---@field merchantID? string
---@field pageNumber? number
---@field pageSize? number
---@field payeeDetails table
---@field payerDetails table
---@field paymentRequestCustomFields? table
---@field paymentRequestID? string
---@field payoutID? string
---@field proprietaryBankTransactionCode? table
---@field rawReference? string
---@field reference? string
---@field ruleID? string
---@field statementReferences? table
---@field status? string
---@field supplementaryData? any
---@field tags? table
---@field theirReference? string
---@field totalPages? number
---@field totalSize? number
---@field transactionAmount table
---@field transactionDate? string
---@field transactionInformation? table
---@field transactionMutability? string
---@field type? string
---@field valueDateTime? string
---@field virtualIBAN? string
---@field yourReference? string

---@class TransactionLoadMatch
---@field id string

---@class TransactionListMatch
---@field account_id string
---@field id string

---@class TransactionCreateData
---@field id string
---@field accountID? string
---@field accountName? string
---@field accountSequenceNumber? number
---@field addressDetails? table
---@field amount? number
---@field amountMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bookingDateTime? string
---@field chargeDetails? table
---@field content? table
---@field counterparty? table
---@field counterpartySummary? string
---@field currency? string
---@field currencyExchange? table
---@field date? string
---@field description? string
---@field enrichment? table
---@field fxAmount? number
---@field fxCurrency? string
---@field fxRate? number
---@field grossAmount table
---@field inserted? string
---@field isoBankTransactionCode? table
---@field merchant? table
---@field merchantID? string
---@field pageNumber? number
---@field pageSize? number
---@field payeeDetails table
---@field payerDetails table
---@field paymentRequestCustomFields? table
---@field paymentRequestID? string
---@field payoutID? string
---@field proprietaryBankTransactionCode? table
---@field rawReference? string
---@field reference? string
---@field ruleID? string
---@field statementReferences? table
---@field status? string
---@field supplementaryData? any
---@field tags? table
---@field theirReference? string
---@field totalPages? number
---@field totalSize? number
---@field transactionAmount table
---@field transactionDate? string
---@field transactionInformation? table
---@field transactionMutability? string
---@field type? string
---@field valueDateTime? string
---@field virtualIBAN? string
---@field yourReference? string

---@class TransactionRemoveMatch
---@field id string

---@class User
---@field clientSessionTimeouts? table
---@field emailAddress string
---@field firstName string
---@field id? string
---@field lastName string
---@field passkeyAdded? boolean
---@field permissions? table
---@field profile? string
---@field rolesWithScope? table
---@field twoFactorEnabled? boolean
---@field userInviteID? string

---@class UserListMatch
---@field clientSessionTimeouts? table
---@field emailAddress? string
---@field firstName? string
---@field id? string
---@field lastName? string
---@field passkeyAdded? boolean
---@field permissions? table
---@field profile? string
---@field rolesWithScope? table
---@field twoFactorEnabled? boolean
---@field userInviteID? string

---@class UserUpdateData
---@field id string
---@field clientSessionTimeouts? table
---@field emailAddress? string
---@field firstName? string
---@field lastName? string
---@field passkeyAdded? boolean
---@field permissions? table
---@field profile? string
---@field rolesWithScope? table
---@field twoFactorEnabled? boolean
---@field userInviteID? string

---@class UserInvite
---@field authorisationStatus? table
---@field failedUserInvites? table
---@field id? string
---@field initialRoleID? string
---@field inviteeEmailAddress? string
---@field inviteeFirstName? string
---@field inviteeLastName? string
---@field inviterEmailAddress? string
---@field inviterFirstName? string
---@field inviterLastName? string
---@field isAuthorised? boolean
---@field isInviteeRegistered? boolean
---@field lastInvited? string
---@field merchantID? string
---@field merchantName? string
---@field message? string
---@field registrationUrl? string
---@field sendInviteEmail? boolean
---@field status? string
---@field user table
---@field userID? string
---@field userInvites? table

---@class UserInviteLoadMatch
---@field id string

---@class UserInviteListMatch
---@field merchant_id string

---@class UserInviteCreateData
---@field id string
---@field authorisationStatus? table
---@field failedUserInvites? table
---@field initialRoleID? string
---@field inviteeEmailAddress? string
---@field inviteeFirstName? string
---@field inviteeLastName? string
---@field inviterEmailAddress? string
---@field inviterFirstName? string
---@field inviterLastName? string
---@field isAuthorised? boolean
---@field isInviteeRegistered? boolean
---@field lastInvited? string
---@field merchantID? string
---@field merchantName? string
---@field message? string
---@field registrationUrl? string
---@field sendInviteEmail? boolean
---@field status? string
---@field user table
---@field userID? string
---@field userInvites? table

---@class UserInviteUpdateData
---@field id string
---@field authorisationStatus? table
---@field failedUserInvites? table
---@field initialRoleID? string
---@field inviteeEmailAddress? string
---@field inviteeFirstName? string
---@field inviteeLastName? string
---@field inviterEmailAddress? string
---@field inviterFirstName? string
---@field inviterLastName? string
---@field isAuthorised? boolean
---@field isInviteeRegistered? boolean
---@field lastInvited? string
---@field merchantID? string
---@field merchantName? string
---@field message? string
---@field registrationUrl? string
---@field sendInviteEmail? boolean
---@field status? string
---@field user? table
---@field userID? string
---@field userInvites? table

---@class UserInviteRemoveMatch
---@field id string

---@class Virtual
---@field accountName? string
---@field accountSupplierName? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field createdBy table
---@field createdByDisplayName? string
---@field currency? string
---@field defaultPaymentRail? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field id? string
---@field identifier table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field name string
---@field physicalAccountID? string
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierSepaInstantStatus? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class VirtualCreateData
---@field account_id string
---@field accountName? string
---@field accountSupplierName? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field createdBy table
---@field createdByDisplayName? string
---@field currency? string
---@field defaultPaymentRail? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field id? string
---@field identifier table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field name string
---@field physicalAccountID? string
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierSepaInstantStatus? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class VirtualUpdateData
---@field account_id string
---@field id string
---@field accountName? string
---@field accountSupplierName? string
---@field availableBalance? number
---@field availableBalanceMinorUnits? number
---@field balance? number
---@field balanceMinorUnits? number
---@field bankName? string
---@field consentID? string
---@field createdBy? table
---@field createdByDisplayName? string
---@field currency? string
---@field defaultPaymentRail? string
---@field displayName? string
---@field expiryDate? string
---@field externalAccountIcon? string
---@field identifier? table
---@field inserted? string
---@field isArchived? boolean
---@field isConnectedAccount? boolean
---@field isDefault? boolean
---@field isTrustAccount? boolean
---@field isVirtual? boolean
---@field lastTransaction? table
---@field lastUpdated? string
---@field merchantID? string
---@field merchantName? string
---@field name? string
---@field physicalAccountID? string
---@field rules? table
---@field submittedPayoutsBalance? number
---@field submittedPayoutsBalanceMinorUnits? number
---@field summary? string
---@field supplierSepaInstantStatus? string
---@field xeroBankFeedConnectionStatus? string
---@field xeroBankFeedLastSyncedAt? string
---@field xeroBankFeedSyncLastFailedAt? string
---@field xeroBankFeedSyncLastFailureReason? string
---@field xeroBankFeedSyncStatus? string
---@field xeroUnsynchronisedTransactionsCount? number

---@class Webhook
---@field destinationUrl? string
---@field emailAddress? string
---@field failedNotificationEmailAddress? string
---@field id? string
---@field isActive? boolean
---@field merchantID? string
---@field notificationMethod? string
---@field resourceTypes? table
---@field retry? boolean
---@field secret? string
---@field version? number

---@class WebhookLoadMatch
---@field id string
---@field merchant_id? string

---@class WebhookListMatch
---@field merchant_id string

---@class WebhookCreateData
---@field destinationUrl? string
---@field emailAddress? string
---@field failedNotificationEmailAddress? string
---@field id? string
---@field isActive? boolean
---@field merchantID? string
---@field notificationMethod? string
---@field resourceTypes? table
---@field retry? boolean
---@field secret? string
---@field version? number

---@class WebhookUpdateData
---@field id string
---@field destinationUrl? string
---@field emailAddress? string
---@field failedNotificationEmailAddress? string
---@field isActive? boolean
---@field merchantID? string
---@field notificationMethod? string
---@field resourceTypes? table
---@field retry? boolean
---@field secret? string
---@field version? number

---@class WebhookRemoveMatch
---@field id string

local M = {}

return M
