// Command Nofrixion-cli is a CLI + REPL for the Nofrixion SDK,
// built on the AQL engine. Positional arguments are joined into a
// single AQL expression and evaluated; with no arguments, falls into
// a REPL. Generated by sdkgen go-cli target.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	eng "github.com/aql-lang/aql/eng/go"
	"github.com/aql-lang/aql/eng/go/parser"
	sdk "github.com/voxgig-sdk/nofrixion-sdk/go"
)

// prompt is the REPL prompt prefix (matches the SDK slug).
const prompt = "nofrixion"

// entitiesHelp is the space-separated entity list shown by :help.
const entitiesHelp = "account batch beneficiaries_create beneficiary beneficiary_group card card_customer_token card_payment card_public_key consent currency direct_debit_batch_submit fx_rate i_payment mandate merchant merchant_authorisation_setting merchant_direct_debit_mandate merchant_pay_by_bank_setting merchant_payment_request_template merchant_token metadata no_frixion_version open_banking payeeverification payment payment_account payment_account_minimal payment_initiation payment_request payment_request_event payment_request_metric payment_request_minimal payment_request_result payment_requests_create payout payout_keyset payout_metric payouts_create payrun report report_result roles_create rule rule_event tag token transaction user user_invite user_invites_create virtual webhook"

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
	client := sdk.NewNofrixionSDK(nil)

	r, err := eng.NewRegistry()
	if err != nil {
		fmt.Fprintf(errOut, "registry: %v\n", err)
		return 1
	}
	registerSDKWords(r, client)
	if err := r.Err(); err != nil {
		fmt.Fprintf(errOut, "word registration: %v\n", err)
		return 1
	}
	r.SetParseFunc(parser.Parse)
	r.InitRootContext()
	r.MarkReady()

	if len(args) > 0 {
		return evalOnce(r, strings.Join(args, " "), out, errOut)
	}
	repl(r, in, out)
	return 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
	values, err := parser.Parse(src)
	if err != nil {
		fmt.Fprintf(errOut, "parse: %v\n", err)
		return 1
	}
	result, err := eng.NewTop(r).Run(values)
	if err != nil {
		fmt.Fprintf(errOut, "error: %v\n", err)
		return 1
	}
	for _, v := range result {
		fmt.Fprintln(out, v.String())
	}
	return 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for {
		fmt.Fprintf(out, "%s> ", prompt)
		if !scanner.Scan() {
			fmt.Fprintln(out)
			return
		}
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		switch line {
		case ":quit", ":q", ":exit":
			return
		case ":help", ":h", ":?":
			fmt.Fprintln(out, "commands: list / load / update <query?> <entity>")
			fmt.Fprintln(out, "entities:", entitiesHelp)
			fmt.Fprintln(out, "meta:     :quit :help")
			continue
		}
		values, err := parser.Parse(line)
		if err != nil {
			fmt.Fprintf(out, "  parse error: %v\n", err)
			continue
		}
		result, err := eng.NewTop(r).Run(values)
		if err != nil {
			fmt.Fprintf(out, "  error: %v\n", err)
			continue
		}
		for _, v := range result {
			fmt.Fprintln(out, v.String())
		}
	}
}
