// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/aql-lang/aql/eng/go"
	sdk "github.com/voxgig-sdk/nofrixion-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.NofrixionSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.NofrixionSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.NofrixionSDK, name string) (sdk.NofrixionEntity, error) {
	switch strings.ToLower(name) {
	case "account":
		return client.Account(nil), nil
	case "beneficiary":
		return client.Beneficiary(nil), nil
	case "cancel":
		return client.Cancel(nil), nil
	case "disable":
		return client.Disable(nil), nil
	case "enable":
		return client.Enable(nil), nil
	case "merchant":
		return client.Merchant(nil), nil
	case "metadata":
		return client.Metadata(nil), nil
	case "no_frixion_biz_biz_models_paging_merchant_direct_debit_mandate_page":
		return client.NoFrixionBizBizModelsPagingMerchantDirectDebitMandatePage(nil), nil
	case "no_frixion_biz_biz_models_paging_payment_request_page":
		return client.NoFrixionBizBizModelsPagingPaymentRequestPage(nil), nil
	case "no_frixion_biz_biz_models_paging_payout_page":
		return client.NoFrixionBizBizModelsPagingPayoutPage(nil), nil
	case "no_frixion_biz_biz_models_paging_payrun_page":
		return client.NoFrixionBizBizModelsPagingPayrunPage(nil), nil
	case "no_frixion_biz_biz_models_paging_rule_events_page":
		return client.NoFrixionBizBizModelsPagingRuleEventsPage(nil), nil
	case "no_frixion_biz_biz_models_paging_rules_page":
		return client.NoFrixionBizBizModelsPagingRulesPage(nil), nil
	case "no_frixion_biz_biz_models_payments_card_payment":
		return client.NoFrixionBizBizModelsPaymentsCardPayment(nil), nil
	case "no_frixion_biz_biz_models_payments_card_public_key":
		return client.NoFrixionBizBizModelsPaymentsCardPublicKey(nil), nil
	case "no_frixion_money_moov_api_features_beneficiaries_beneficiaries":
		return client.NoFrixionMoneyMoovApiFeaturesBeneficiariesBeneficiaries(nil), nil
	case "no_frixion_money_moov_api_features_payment_requests_payment":
		return client.NoFrixionMoneyMoovApiFeaturesPaymentRequestsPayment(nil), nil
	case "no_frixion_money_moov_api_features_permissions_roles_create":
		return client.NoFrixionMoneyMoovApiFeaturesPermissionsRolesCreate(nil), nil
	case "no_frixion_money_moov_api_features_user_invites_create":
		return client.NoFrixionMoneyMoovApiFeaturesUserInvitesCreate(nil), nil
	case "no_frixion_money_moov_models_authorisation_settings_merchant":
		return client.NoFrixionMoneyMoovModelsAuthorisationSettingsMerchant(nil), nil
	case "no_frixion_money_moov_models_batch_payout":
		return client.NoFrixionMoneyMoovModelsBatchPayout(nil), nil
	case "no_frixion_money_moov_models_beneficiary_group_page":
		return client.NoFrixionMoneyMoovModelsBeneficiaryGroupPage(nil), nil
	case "no_frixion_money_moov_models_beneficiary_page":
		return client.NoFrixionMoneyMoovModelsBeneficiaryPage(nil), nil
	case "no_frixion_money_moov_models_card_customer_token":
		return client.NoFrixionMoneyMoovModelsCardCustomerToken(nil), nil
	case "no_frixion_money_moov_models_currency_currency_info":
		return client.NoFrixionMoneyMoovModelsCurrencyCurrencyInfo(nil), nil
	case "no_frixion_money_moov_models_direct_debit_batch_submit":
		return client.NoFrixionMoneyMoovModelsDirectDebitBatchSubmit(nil), nil
	case "no_frixion_money_moov_models_fx_rate":
		return client.NoFrixionMoneyMoovModelsFxRate(nil), nil
	case "no_frixion_money_moov_models_i_payment":
		return client.NoFrixionMoneyMoovModelsIPayment(nil), nil
	case "no_frixion_money_moov_models_mandates_mandate":
		return client.NoFrixionMoneyMoovModelsMandatesMandate(nil), nil
	case "no_frixion_money_moov_models_merchant":
		return client.NoFrixionMoneyMoovModelsMerchant(nil), nil
	case "no_frixion_money_moov_models_merchant_page":
		return client.NoFrixionMoneyMoovModelsMerchantPage(nil), nil
	case "no_frixion_money_moov_models_merchant_pay_by_bank_setting":
		return client.NoFrixionMoneyMoovModelsMerchantPayByBankSetting(nil), nil
	case "no_frixion_money_moov_models_merchant_token":
		return client.NoFrixionMoneyMoovModelsMerchantToken(nil), nil
	case "no_frixion_money_moov_models_merchant_token_page":
		return client.NoFrixionMoneyMoovModelsMerchantTokenPage(nil), nil
	case "no_frixion_money_moov_models_no_frixion_version":
		return client.NoFrixionMoneyMoovModelsNoFrixionVersion(nil), nil
	case "no_frixion_money_moov_models_open_banking_account":
		return client.NoFrixionMoneyMoovModelsOpenBankingAccount(nil), nil
	case "no_frixion_money_moov_models_open_banking_consent":
		return client.NoFrixionMoneyMoovModelsOpenBankingConsent(nil), nil
	case "no_frixion_money_moov_models_open_banking_transaction":
		return client.NoFrixionMoneyMoovModelsOpenBankingTransaction(nil), nil
	case "no_frixion_money_moov_models_payment":
		return client.NoFrixionMoneyMoovModelsPayment(nil), nil
	case "no_frixion_money_moov_models_payment_account_minimal_page":
		return client.NoFrixionMoneyMoovModelsPaymentAccountMinimalPage(nil), nil
	case "no_frixion_money_moov_models_payment_account_page":
		return client.NoFrixionMoneyMoovModelsPaymentAccountPage(nil), nil
	case "no_frixion_money_moov_models_payment_initiation":
		return client.NoFrixionMoneyMoovModelsPaymentInitiation(nil), nil
	case "no_frixion_money_moov_models_payment_request_event":
		return client.NoFrixionMoneyMoovModelsPaymentRequestEvent(nil), nil
	case "no_frixion_money_moov_models_payment_request_metric":
		return client.NoFrixionMoneyMoovModelsPaymentRequestMetric(nil), nil
	case "no_frixion_money_moov_models_payment_request_minimal":
		return client.NoFrixionMoneyMoovModelsPaymentRequestMinimal(nil), nil
	case "no_frixion_money_moov_models_payment_request_result":
		return client.NoFrixionMoneyMoovModelsPaymentRequestResult(nil), nil
	case "no_frixion_money_moov_models_payment_requests_merchant_payment":
		return client.NoFrixionMoneyMoovModelsPaymentRequestsMerchantPayment(nil), nil
	case "no_frixion_money_moov_models_payment_requests_merchant_payment2":
		return client.NoFrixionMoneyMoovModelsPaymentRequestsMerchantPayment2(nil), nil
	case "no_frixion_money_moov_models_payment_requests_merchant_payment3":
		return client.NoFrixionMoneyMoovModelsPaymentRequestsMerchantPayment3(nil), nil
	case "no_frixion_money_moov_models_payment_requests_merchant_payment4":
		return client.NoFrixionMoneyMoovModelsPaymentRequestsMerchantPayment4(nil), nil
	case "no_frixion_money_moov_models_payout_keyset_page":
		return client.NoFrixionMoneyMoovModelsPayoutKeysetPage(nil), nil
	case "no_frixion_money_moov_models_payout_metric":
		return client.NoFrixionMoneyMoovModelsPayoutMetric(nil), nil
	case "no_frixion_money_moov_models_payouts_payouts_create":
		return client.NoFrixionMoneyMoovModelsPayoutsPayoutsCreate(nil), nil
	case "no_frixion_money_moov_models_payrun":
		return client.NoFrixionMoneyMoovModelsPayrun(nil), nil
	case "no_frixion_money_moov_models_report_result":
		return client.NoFrixionMoneyMoovModelsReportResult(nil), nil
	case "no_frixion_money_moov_models_rule":
		return client.NoFrixionMoneyMoovModelsRule(nil), nil
	case "no_frixion_money_moov_models_transaction":
		return client.NoFrixionMoneyMoovModelsTransaction(nil), nil
	case "no_frixion_money_moov_models_transaction_page":
		return client.NoFrixionMoneyMoovModelsTransactionPage(nil), nil
	case "no_frixion_money_moov_models_user_invite":
		return client.NoFrixionMoneyMoovModelsUserInvite(nil), nil
	case "no_frixion_money_moov_models_user_invite_page":
		return client.NoFrixionMoneyMoovModelsUserInvitePage(nil), nil
	case "no_frixion_money_moov_models_user_page":
		return client.NoFrixionMoneyMoovModelsUserPage(nil), nil
	case "no_frixion_money_moov_models_webhook":
		return client.NoFrixionMoneyMoovModelsWebhook(nil), nil
	case "open_banking":
		return client.OpenBanking(nil), nil
	case "payeeverification":
		return client.Payeeverification(nil), nil
	case "payment_request":
		return client.PaymentRequest(nil), nil
	case "payout":
		return client.Payout(nil), nil
	case "payrun":
		return client.Payrun(nil), nil
	case "reject":
		return client.Reject(nil), nil
	case "report":
		return client.Report(nil), nil
	case "rule":
		return client.Rule(nil), nil
	case "send":
		return client.Send(nil), nil
	case "sendbeneficiary":
		return client.Sendbeneficiary(nil), nil
	case "tag":
		return client.Tag(nil), nil
	case "token":
		return client.Token(nil), nil
	case "transaction":
		return client.Transaction(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_invite":
		return client.UserInvite(nil), nil
	case "virtual":
		return client.Virtual(nil), nil
	case "webhook":
		return client.Webhook(nil), nil
	case "whoami":
		return client.Whoami(nil), nil
	case "whoamitrustedapp":
		return client.Whoamitrustedapp(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
