// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/aql-lang/aql/eng/go"
	sdk "github.com/voxgig-sdk/nofrixion-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.NofrixionSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.NofrixionSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.NofrixionSDK, name string) (sdk.NofrixionEntity, error) {
	switch strings.ToLower(name) {
	case "account":
		return client.Account(nil), nil
	case "batch":
		return client.Batch(nil), nil
	case "beneficiaries_create":
		return client.BeneficiariesCreate(nil), nil
	case "beneficiary":
		return client.Beneficiary(nil), nil
	case "beneficiary_group":
		return client.BeneficiaryGroup(nil), nil
	case "card":
		return client.Card(nil), nil
	case "card_customer_token":
		return client.CardCustomerToken(nil), nil
	case "card_payment":
		return client.CardPayment(nil), nil
	case "card_public_key":
		return client.CardPublicKey(nil), nil
	case "consent":
		return client.Consent(nil), nil
	case "currency":
		return client.Currency(nil), nil
	case "direct_debit_batch_submit":
		return client.DirectDebitBatchSubmit(nil), nil
	case "fx_rate":
		return client.FxRate(nil), nil
	case "i_payment":
		return client.IPayment(nil), nil
	case "mandate":
		return client.Mandate(nil), nil
	case "merchant":
		return client.Merchant(nil), nil
	case "merchant_authorisation_setting":
		return client.MerchantAuthorisationSetting(nil), nil
	case "merchant_direct_debit_mandate":
		return client.MerchantDirectDebitMandate(nil), nil
	case "merchant_pay_by_bank_setting":
		return client.MerchantPayByBankSetting(nil), nil
	case "merchant_payment_request_template":
		return client.MerchantPaymentRequestTemplate(nil), nil
	case "merchant_token":
		return client.MerchantToken(nil), nil
	case "metadata":
		return client.Metadata(nil), nil
	case "no_frixion_version":
		return client.NoFrixionVersion(nil), nil
	case "open_banking":
		return client.OpenBanking(nil), nil
	case "payeeverification":
		return client.Payeeverification(nil), nil
	case "payment":
		return client.Payment(nil), nil
	case "payment_account":
		return client.PaymentAccount(nil), nil
	case "payment_account_minimal":
		return client.PaymentAccountMinimal(nil), nil
	case "payment_initiation":
		return client.PaymentInitiation(nil), nil
	case "payment_request":
		return client.PaymentRequest(nil), nil
	case "payment_request_event":
		return client.PaymentRequestEvent(nil), nil
	case "payment_request_metric":
		return client.PaymentRequestMetric(nil), nil
	case "payment_request_minimal":
		return client.PaymentRequestMinimal(nil), nil
	case "payment_request_result":
		return client.PaymentRequestResult(nil), nil
	case "payment_requests_create":
		return client.PaymentRequestsCreate(nil), nil
	case "payout":
		return client.Payout(nil), nil
	case "payout_keyset":
		return client.PayoutKeyset(nil), nil
	case "payout_metric":
		return client.PayoutMetric(nil), nil
	case "payouts_create":
		return client.PayoutsCreate(nil), nil
	case "payrun":
		return client.Payrun(nil), nil
	case "report":
		return client.Report(nil), nil
	case "report_result":
		return client.ReportResult(nil), nil
	case "roles_create":
		return client.RolesCreate(nil), nil
	case "rule":
		return client.Rule(nil), nil
	case "rule_event":
		return client.RuleEvent(nil), nil
	case "tag":
		return client.Tag(nil), nil
	case "token":
		return client.Token(nil), nil
	case "transaction":
		return client.Transaction(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_invite":
		return client.UserInvite(nil), nil
	case "user_invites_create":
		return client.UserInvitesCreate(nil), nil
	case "virtual":
		return client.Virtual(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
