// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/nofrixion-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"account | batch | beneficiary | beneficiary_group | card | card_customer_token | card_payment | card_public_key | consent | currency | direct_debit_batch_submit | fx_rate | i_payment | mandate | merchant | merchant_authorisation_setting | merchant_direct_debit_mandate_page | merchant_pay_by_bank_setting | merchant_payment_request_template | merchant_token | metadata | no_frixion_version | open_banking | payeeverification | payment | payment_account | payment_account_minimal | payment_initiation | payment_request | payment_request_event | payment_request_metric | payment_request_minimal | payment_request_result | payout | payout_keyset_page | payout_metric | payrun | report | report_result | role | rule | rule_event | tag | token | transaction | user | user_invite | virtual | webhook"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.NofrixionSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "nofrixion_list",
		Description: "List records from Nofrixion. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "nofrixion_load",
		Description: "Load a single record from Nofrixion. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.NofrixionSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.NofrixionSDK, name string) (sdk.NofrixionEntity, error) {
	switch strings.ToLower(name) {
	case "account":
		return client.Account(nil), nil
	case "batch":
		return client.Batch(nil), nil
	case "beneficiary":
		return client.Beneficiary(nil), nil
	case "beneficiary_group":
		return client.BeneficiaryGroup(nil), nil
	case "card":
		return client.Card(nil), nil
	case "card_customer_token":
		return client.CardCustomerToken(nil), nil
	case "card_payment":
		return client.CardPayment(nil), nil
	case "card_public_key":
		return client.CardPublicKey(nil), nil
	case "consent":
		return client.Consent(nil), nil
	case "currency":
		return client.Currency(nil), nil
	case "direct_debit_batch_submit":
		return client.DirectDebitBatchSubmit(nil), nil
	case "fx_rate":
		return client.FxRate(nil), nil
	case "i_payment":
		return client.IPayment(nil), nil
	case "mandate":
		return client.Mandate(nil), nil
	case "merchant":
		return client.Merchant(nil), nil
	case "merchant_authorisation_setting":
		return client.MerchantAuthorisationSetting(nil), nil
	case "merchant_direct_debit_mandate_page":
		return client.MerchantDirectDebitMandatePage(nil), nil
	case "merchant_pay_by_bank_setting":
		return client.MerchantPayByBankSetting(nil), nil
	case "merchant_payment_request_template":
		return client.MerchantPaymentRequestTemplate(nil), nil
	case "merchant_token":
		return client.MerchantToken(nil), nil
	case "metadata":
		return client.Metadata(nil), nil
	case "no_frixion_version":
		return client.NoFrixionVersion(nil), nil
	case "open_banking":
		return client.OpenBanking(nil), nil
	case "payeeverification":
		return client.Payeeverification(nil), nil
	case "payment":
		return client.Payment(nil), nil
	case "payment_account":
		return client.PaymentAccount(nil), nil
	case "payment_account_minimal":
		return client.PaymentAccountMinimal(nil), nil
	case "payment_initiation":
		return client.PaymentInitiation(nil), nil
	case "payment_request":
		return client.PaymentRequest(nil), nil
	case "payment_request_event":
		return client.PaymentRequestEvent(nil), nil
	case "payment_request_metric":
		return client.PaymentRequestMetric(nil), nil
	case "payment_request_minimal":
		return client.PaymentRequestMinimal(nil), nil
	case "payment_request_result":
		return client.PaymentRequestResult(nil), nil
	case "payout":
		return client.Payout(nil), nil
	case "payout_keyset_page":
		return client.PayoutKeysetPage(nil), nil
	case "payout_metric":
		return client.PayoutMetric(nil), nil
	case "payrun":
		return client.Payrun(nil), nil
	case "report":
		return client.Report(nil), nil
	case "report_result":
		return client.ReportResult(nil), nil
	case "role":
		return client.Role(nil), nil
	case "rule":
		return client.Rule(nil), nil
	case "rule_event":
		return client.RuleEvent(nil), nil
	case "tag":
		return client.Tag(nil), nil
	case "token":
		return client.Token(nil), nil
	case "transaction":
		return client.Transaction(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_invite":
		return client.UserInvite(nil), nil
	case "virtual":
		return client.Virtual(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
